---
name: Release

on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*

jobs:

    publish:

        name: Publish to PyPI

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v2

            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'

            - name: Install flit
              run: |
                  python -m pip install flit==3.7.1

            - name: Build and publish
              run: |
                  flit publish
              env:
                  FLIT_USERNAME: __token__
                  FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

            - uses: softprops/action-gh-release@v0.1.14
              name: Create release
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  files: |
                      dist/*
                  generate_release_notes: true
